In [110]:
import pandas as pd

In [111]:
df = pd.read_csv("../Data/Raw Data/us_daily.csv")
df.head()

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,lastModified,recovered,total,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease,hash
0,20210307,56,28755524.0,74579770.0,11808.0,40212.0,878613.0,8137.0,45475.0,2801.0,...,2021-03-07T24:00:00Z,NaN,0,0,839,726,130414,41265,1156241,8b26839690cd05c0cef69cb9ed85641a76b5e78e
1,20210306,56,28714259.0,74449356.0,11783.0,41401.0,877887.0,8409.0,45453.0,2811.0,...,2021-03-06T24:00:00Z,NaN,0,0,1674,503,142201,59620,1409138,d0c0482ea549c9d5c04a7c86acb6fc6a8095a592
2,20210305,56,28654639.0,74307155.0,12213.0,42541.0,877384.0,8634.0,45373.0,2889.0,...,2021-03-05T24:00:00Z,NaN,0,0,2221,2781,271917,68787,1744417,a35ea4289cec4bb55c9f29ae04ec0fd5ac4e0222
3,20210304,56,28585852.0,74035238.0,12405.0,44172.0,874603.0,8970.0,45293.0,2973.0,...,2021-03-04T24:00:00Z,NaN,0,0,1743,1530,177957,65487,1590984,a19ad6379a653834cbda3093791ad2c3b9fab5ff
4,20210303,56,28520365.0,73857281.0,11778.0,45462.0,873073.0,9359.0,45214.0,3094.0,...,2021-03-03T24:00:00Z,NaN,0,0,2449,2172,267001,66836,1406795,9e1d2afda1b0ec243060d6f68a7134d011c0cb2a

In [112]:
df = df.drop(['dateChecked', 'lastModified', 'recovered', 'total', 'posNeg', 'hash'], axis= 1)
df.tail()

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,death,hospitalized,totalTestResults,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
415,20200117,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0
416,20200116,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0
417,20200115,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0
418,20200114,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0
419,20200113,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0

In [113]:
columns = df.columns
for i in columns:
    df[i] = df[i].fillna(0)   
    df[i] = df[i].astype(int)
    df[i]

In [114]:
Date = []
for i in df['date']:
    date_object = pd.to_datetime(i, format='%Y%m%d')
    formatted_date = date_object.strftime('%Y-%m-%d')
    Date.append(formatted_date)
df['date'] = Date

In [116]:
df.head()

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,death,hospitalized,totalTestResults,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,2021-03-07,56,28755524,74579770,11808,40212,878613,8137,45475,2801,4281,515142,878613,363789451,839,726,130414,41265,1156241
1,2021-03-06,56,28714259,74449356,11783,41401,877887,8409,45453,2811,4280,514303,877887,362633210,1674,503,142201,59620,1409138
2,2021-03-05,56,28654639,74307155,12213,42541,877384,8634,45373,2889,4275,512629,877384,361224072,2221,2781,271917,68787,1744417
3,2021-03-04,56,28585852,74035238,12405,44172,874603,8970,45293,2973,4267,510408,874603,359479655,1743,1530,177957,65487,1590984
4,2021-03-03,56,28520365,73857281,11778,45462,873073,9359,45214,3094,4260,508665,873073,357888671,2449,2172,267001,66836,1406795

In [118]:
df.to_csv("../Data/Clean Data/US_Daily_Cases.csv", index= False)